spring:
  datasource:
    url: postgres://iejujafyozsqpk:35f27bcee0e002e36df48222b105b68f198e1bb537b464fbf129d31ce5541744@ec2-54-160-200-167.compute-1.amazonaws.com:5432/d8sddlcbvh96vh
    driver-class-name: org.postgresql.Driver
    username: iejujafyozsqpk
    password: 35f27bcee0e002e36df48222b105b68f198e1bb537b464fbf129d31ce5541744
  sql:
    init:
      platform: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create